language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script:
  - ./travis.sh

env:
  matrix:
    - TARGET=CI

cache:
  directories:
    - $HOME/.m2/repository
    # for integration tests and analysis
    - $HOME/.sonar

notifications:
  email: false
  webhooks:
    - secure: "guSRJ2VAqYrQoYWpVWZ6kiFgfYOu0+W52hvTSviGIDNk0EY2dtqiO3Ya17eL0cqMXa9OTEKaE/sGr3H1lnBR0YKAejfqRIA6KlT7Y/iCICMcTuGRquVQSr8vfK4wdtiOXIDUGEtnFZ2ePaE+KMywYfybasbb5a0TpUng4zASfJw="

